### ISSUE TITLE
Failed to run main.py

### ISSUE THREAD

**Issue by ZTMIDGO** [pushpendra910/Stable-Diffusion#2]
Error message

Traceback (most recent call last):
  File "D:\python\diffusion-tflite\main.py", line 32, in <module>
    model=Instanciate_Model.LoadModel(512,512,False,True)
  File "D:\python\diffusion-tflite\main.py", line 30, in LoadModel
    return StableDiffusion(img_height,img_weight,jit_compile,download_weights)
  File "D:\python\diffusion-tflite\stable_diffusion_tf\stable_diffusion.py", line 24, in __init__
    text_encoder, diffusion_model, decoder, encoder = get_models(img_height, img_width, download_weights=download_weights)
  File "D:\python\diffusion-tflite\stable_diffusion_tf\stable_diffusion.py", line 270, in get_models
    diffusion_model.load_weights(diffusion_model_weights_fpath)
  File "D:\python\diffusion-tflite\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\python\diffusion-tflite\venv\lib\site-packages\keras\mixed_precision\autocast_variable.py", line 227, in _apply_assign_update
    assign_op = update_fn(value, use_locking, name, False)
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

**Comment by pushpendra910** [comment]
This error is encountered because of the Tensorflow and GPU. Make sure you are installing all the requirements without any version changes or warnings.
